server:
  port: 8080
dubbo:
  application:
    name: api-service
  registry:
    address: nacos://172.16.72.132:8848?namespace=e8942369-0b37-44a0-b711-3927db1796ad
    username: nacos
    password: nacos
  consumer:
    check: false
  scan:
    base-packages: com.wq.dubbo
  protocol:
    name: dubbo
    port: -1
  cloud:
    subscribed-services: friend-service,account-service
spring:
  application:
    name: api-service
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://172.16.72.132:3306/mytest?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2b8&useUnicode=true
    username: root
    password: 12345