server:
  port: 8082
dubbo:
  application:
    name: friend-service
  registry:
    address: nacos://172.16.72.132:8848?namespace=df115cd8-6506-4417-bc91-4ee08a8ec2f1
    username: nacos
    password: nacos
  consumer:
    check: false
  scan:
    base-packages: com.wq.dubbo
  protocol:
    name: dubbo
    port: -1
  cloud:
    subscribed-services: api-service,friend-service,account-service
spring:
  application:
    name: friend-service
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://172.16.72.132:3306/mytest?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2b8&useUnicode=true
    username: root
    password: 123456