server:
  port: 8082
dubbo:
  application:
    name: friend-service
  registry:
    address: nacos://172.16.72.133:8848?namespace=e8942369-0b37-44a0-b711-3927db1796ad
    username: nacos
    password: nacos
  consumer:
    check: false
  scan:
    base-packages: com.wq.dubbo
  protocol:
    name: dubbo
    port: -1
  cloud:
    subscribed-services: api-service,friend-service,account-service
spring:
  application:
    name: friend-service
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://172.16.72.133:3306/mytest?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2b8&useUnicode=true
    username: root
    password: 123456
  cloud:
    stream:
      function:
        definition: broadcastMessage
      kafka:
        binder:
          brokers: 172.16.72.133:9092
          auto-create-topics: true
          configuration:
            key:
              serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      bindings:
        broadcastMessage-in-0:
          destination: test
#          group: test-topic-friend
          group: test-topic-account
          content-type: application/json
          consumer:
            maxAttempts: 1 # 尝试消费该消息的最大次数（消息消费失败后，发布者会重新投递）。默认3
            backOffInitialInterval: 1000 # 重试消费消息的初始化间隔时间。默认1s，即第一次重试消费会在1s后进行
            backOffMultiplier: 2 # 相邻两次重试之间的间隔时间的倍数。默认2
            backOffMaxInterval: 10000 # 下一次尝试重试的最大时间间隔，默认为10000ms，即10s