server:
  port: 8082
dubbo:
  application:
    name: friend-service
  registry:
    address: nacos://172.16.72.133:8848?namespace=e8942369-0b37-44a0-b711-3927db1796ad
    username: nacos
    password: nacos
  consumer:
    check: false
  scan:
    base-packages: com.wq.dubbo
  protocol:
    name: dubbo
    port: -1
  cloud:
    subscribed-services: api-service,friend-service,account-service
spring:
  application:
    name: friend-service
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://172.16.72.133:3306/mytest?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2b8&useUnicode=true
    username: root
    password: 123456
  cloud:
    stream:
      function:
        definition: broadcastMessage;delayMessage
      rocketmq:
        binder:
          name-server: 172.16.72.133:9876
        bindings:
          broadcastMessage-in-0:
            consumer:
              messageModel: BROADCASTING
          delayMessage-in-0:
            consumer:
              messageModel: BROADCASTING
      bindings:
        broadcastMessage-in-0:
          destination: broadcast
          group: broadcast-consumer
        delayMessage-in-0:
          destination: delaymessage
          group: delay-consumer